// <auto-generated />
using LostArk.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LostArk.Api.Migrations
{
    [DbContext(typeof(LostArkDbContext))]
    [Migration("20220425233617_InitialSetup")]
    partial class InitialSetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LostArk.Api.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bnoc",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Skex",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bnocx",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bnocy",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bnocz",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("LostArk.Api.Entities.CharacterTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterTaskTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CharacterTaskTypeId");

                    b.ToTable("CharacterTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterId = 1,
                            CharacterTaskTypeId = 1,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 2,
                            CharacterId = 1,
                            CharacterTaskTypeId = 1,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 3,
                            CharacterId = 1,
                            CharacterTaskTypeId = 2,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 4,
                            CharacterId = 1,
                            CharacterTaskTypeId = 2,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 5,
                            CharacterId = 1,
                            CharacterTaskTypeId = 3,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 6,
                            CharacterId = 1,
                            CharacterTaskTypeId = 3,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 7,
                            CharacterId = 1,
                            CharacterTaskTypeId = 3,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 8,
                            CharacterId = 1,
                            CharacterTaskTypeId = 4,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 9,
                            CharacterId = 1,
                            CharacterTaskTypeId = 5,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 10,
                            CharacterId = 1,
                            CharacterTaskTypeId = 6,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 11,
                            CharacterId = 1,
                            CharacterTaskTypeId = 7,
                            IsCompleted = false,
                            Period = 1
                        },
                        new
                        {
                            Id = 12,
                            CharacterId = 2,
                            CharacterTaskTypeId = 1,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 13,
                            CharacterId = 2,
                            CharacterTaskTypeId = 1,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 14,
                            CharacterId = 2,
                            CharacterTaskTypeId = 2,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 15,
                            CharacterId = 2,
                            CharacterTaskTypeId = 2,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 16,
                            CharacterId = 2,
                            CharacterTaskTypeId = 3,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 17,
                            CharacterId = 2,
                            CharacterTaskTypeId = 3,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 18,
                            CharacterId = 2,
                            CharacterTaskTypeId = 3,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 19,
                            CharacterId = 2,
                            CharacterTaskTypeId = 4,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 20,
                            CharacterId = 2,
                            CharacterTaskTypeId = 5,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 21,
                            CharacterId = 2,
                            CharacterTaskTypeId = 6,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 22,
                            CharacterId = 2,
                            CharacterTaskTypeId = 7,
                            IsCompleted = false,
                            Period = 1
                        },
                        new
                        {
                            Id = 23,
                            CharacterId = 3,
                            CharacterTaskTypeId = 1,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 24,
                            CharacterId = 3,
                            CharacterTaskTypeId = 1,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 25,
                            CharacterId = 3,
                            CharacterTaskTypeId = 2,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 26,
                            CharacterId = 3,
                            CharacterTaskTypeId = 2,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 27,
                            CharacterId = 3,
                            CharacterTaskTypeId = 3,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 28,
                            CharacterId = 3,
                            CharacterTaskTypeId = 3,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 29,
                            CharacterId = 3,
                            CharacterTaskTypeId = 3,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 30,
                            CharacterId = 3,
                            CharacterTaskTypeId = 4,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 31,
                            CharacterId = 3,
                            CharacterTaskTypeId = 5,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 32,
                            CharacterId = 3,
                            CharacterTaskTypeId = 6,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 33,
                            CharacterId = 3,
                            CharacterTaskTypeId = 7,
                            IsCompleted = false,
                            Period = 1
                        },
                        new
                        {
                            Id = 34,
                            CharacterId = 4,
                            CharacterTaskTypeId = 1,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 35,
                            CharacterId = 4,
                            CharacterTaskTypeId = 1,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 36,
                            CharacterId = 4,
                            CharacterTaskTypeId = 2,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 37,
                            CharacterId = 4,
                            CharacterTaskTypeId = 2,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 38,
                            CharacterId = 4,
                            CharacterTaskTypeId = 3,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 39,
                            CharacterId = 4,
                            CharacterTaskTypeId = 3,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 40,
                            CharacterId = 4,
                            CharacterTaskTypeId = 3,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 41,
                            CharacterId = 4,
                            CharacterTaskTypeId = 4,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 42,
                            CharacterId = 4,
                            CharacterTaskTypeId = 5,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 43,
                            CharacterId = 4,
                            CharacterTaskTypeId = 6,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 44,
                            CharacterId = 4,
                            CharacterTaskTypeId = 7,
                            IsCompleted = false,
                            Period = 1
                        },
                        new
                        {
                            Id = 45,
                            CharacterId = 5,
                            CharacterTaskTypeId = 1,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 46,
                            CharacterId = 5,
                            CharacterTaskTypeId = 1,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 47,
                            CharacterId = 5,
                            CharacterTaskTypeId = 2,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 48,
                            CharacterId = 5,
                            CharacterTaskTypeId = 2,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 49,
                            CharacterId = 5,
                            CharacterTaskTypeId = 3,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 50,
                            CharacterId = 5,
                            CharacterTaskTypeId = 3,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 51,
                            CharacterId = 5,
                            CharacterTaskTypeId = 3,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 52,
                            CharacterId = 5,
                            CharacterTaskTypeId = 4,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 53,
                            CharacterId = 5,
                            CharacterTaskTypeId = 5,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 54,
                            CharacterId = 5,
                            CharacterTaskTypeId = 6,
                            IsCompleted = false,
                            Period = 0
                        },
                        new
                        {
                            Id = 55,
                            CharacterId = 5,
                            CharacterTaskTypeId = 7,
                            IsCompleted = false,
                            Period = 1
                        });
                });

            modelBuilder.Entity("LostArk.Api.Entities.CharacterTaskType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CharacterTaskTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chaos Dungeon"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Guardian Raid"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Una's Daily"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Event"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Rapport"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Guild"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Una's Weekly"
                        });
                });

            modelBuilder.Entity("LostArk.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "BNOC"
                        });
                });

            modelBuilder.Entity("LostArk.Api.Entities.Character", b =>
                {
                    b.HasOne("LostArk.Api.Entities.User", null)
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LostArk.Api.Entities.CharacterTask", b =>
                {
                    b.HasOne("LostArk.Api.Entities.Character", null)
                        .WithMany("CharacterTasks")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LostArk.Api.Entities.CharacterTaskType", "CharacterTaskType")
                        .WithMany()
                        .HasForeignKey("CharacterTaskTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterTaskType");
                });

            modelBuilder.Entity("LostArk.Api.Entities.Character", b =>
                {
                    b.Navigation("CharacterTasks");
                });

            modelBuilder.Entity("LostArk.Api.Entities.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
